language: objective-c
env:
 global:
  - ARTIFACTS_AWS_REGION=us-west-2
  - ARTIFACTS_S3_BUCKET=lime-artifacts
  - secure: DXYUyMpbecZVlLUHHSrTFyUeaOor2hBIktXgv2AnwbzTgiJeFshUbWA0hu2j3pnGDNlJJpmrdyKJPTsT1hGFZ9tLm5J6Q8j4wA04GBp+dJl0+7RBs/R767XcyIRkJNw4a1hZJCQgv++wWvJ4GhW/KM1uUUHL5dh+McfNBz6SXLs=
  - secure: f0ps0Vor8x1p6rdzpAP67o6HkMIO2e3qFUiYIj+QJXkdzmmy7V3UHW3NxkOerzsiVkxksmB2MOocRCVlseWP72i/4qPrw/r8BpkmkO1SY/HdR1yv0g0DHwJw8i/zhRF390dvNQh/HR0SZrAeDQvKapwzkvQkUvwwp51O5xBLMbs=
before_install:
- wget -c http://nekovm.org/_media/neko-2.0.0-osx.tar.gz
- sudo mkdir /usr/lib/neko
- sudo tar xvzf neko-2.0.0-osx.tar.gz -C /usr/lib/neko --strip-components=1
- sudo ln -s /usr/lib/neko/neko /usr/bin/neko
- sudo ln -s /usr/lib/neko/nekoc /usr/bin/nekoc
- sudo ln -s /usr/lib/neko/nekotools /usr/bin/nekotools
- sudo ln -s /usr/lib/neko/libneko.so /usr/lib/libneko.so
- wget -c http://haxe.org/file/haxe-3.0.1-osx.tar.gz
- sudo mkdir /usr/lib/haxe
- sudo tar xvzf haxe-3.0.1-osx.tar.gz -C /usr/lib/haxe --strip-components=1
- sudo ln -s /usr/lib/haxe/haxe /usr/bin/haxe
- sudo ln -s /usr/lib/haxe/haxelib /usr/bin/haxelib
- mkdir ~/haxelib
- haxelib setup ~/haxelib
- git clone https://github.com/openfl/hxlibc ~/hxlibc
- haxelib dev hxlibc ~/hxlibc
- git clone https://github.com/openfl/lime-build ~/lime-build
- haxelib dev lime-build ~/lime-build
- haxelib dev lime $(pwd)
- gem install travis-artifacts --no-ri --no-rdoc
script:
- haxelib run lime rebuild mac
- haxelib run lime rebuild ios
after_success:
- travis-artifacts upload --path ndll/Mac/lime.ndll --target-path artifacts/$TRAVIS_COMMIT
- travis-artifacts upload --path ndll/Mac/lime-debug.ndll --target-path artifacts/$TRAVIS_COMMIT
- travis-artifacts upload --path ndll/Mac64/lime.ndll --target-path artifacts/$TRAVIS_COMMIT
- travis-artifacts upload --path ndll/Mac64/lime-debug.ndll --target-path artifacts/$TRAVIS_COMMIT
- travis-artifacts upload --path ndll/iPhone/liblime.iphoneos.a --target-path artifacts/$TRAVIS_COMMIT
- travis-artifacts upload --path ndll/iPhone/liblime.iphoneos-v7.a --target-path artifacts/$TRAVIS_COMMIT
- travis-artifacts upload --path ndll/iPhone/liblime.iphonesim.a --target-path artifacts/$TRAVIS_COMMIT
- travis-artifacts upload --path ndll/iPhone/liblime-debug.iphoneos.a --target-path artifacts/$TRAVIS_COMMIT
- travis-artifacts upload --path ndll/iPhone/liblime-debug.iphoneos-v7.a --target-path artifacts/$TRAVIS_COMMIT
- travis-artifacts upload --path ndll/iPhone/liblime-debug.iphonesim.a --target-path artifacts/$TRAVIS_COMMIT
- wget -qO- http://www.openfl.org/lime-post-hook.php?commit=$TRAVIS_COMMIT
